// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ai_actions.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createAction = `-- name: CreateAction :one
INSERT INTO ai_actions (message_id, user_id, position, kind, payload, status)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, message_id, user_id, position, kind, payload, status, result, created_at
`

type CreateActionParams struct {
	MessageID uuid.UUID `json:"message_id"`
	UserID    uuid.UUID `json:"user_id"`
	Position  int32     `json:"position"`
	Kind      string    `json:"kind"`
	Payload   []byte    `json:"payload"`
	Status    string    `json:"status"`
}

func (q *Queries) CreateAction(ctx context.Context, arg CreateActionParams) (AiAction, error) {
	row := q.db.QueryRow(ctx, createAction,
		arg.MessageID,
		arg.UserID,
		arg.Position,
		arg.Kind,
		arg.Payload,
		arg.Status,
	)
	var i AiAction
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.UserID,
		&i.Position,
		&i.Kind,
		&i.Payload,
		&i.Status,
		&i.Result,
		&i.CreatedAt,
	)
	return i, err
}

const getAction = `-- name: GetAction :one
SELECT id, message_id, user_id, position, kind, payload, status, result, created_at FROM ai_actions
WHERE id = $1 AND user_id = $2
`

type GetActionParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetAction(ctx context.Context, arg GetActionParams) (AiAction, error) {
	row := q.db.QueryRow(ctx, getAction, arg.ID, arg.UserID)
	var i AiAction
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.UserID,
		&i.Position,
		&i.Kind,
		&i.Payload,
		&i.Status,
		&i.Result,
		&i.CreatedAt,
	)
	return i, err
}

const listActionsByMessages = `-- name: ListActionsByMessages :many
SELECT id, message_id, user_id, position, kind, payload, status, result, created_at FROM ai_actions
WHERE message_id = ANY($1::uuid[])
ORDER BY message_id, position
`

func (q *Queries) ListActionsByMessages(ctx context.Context, dollar_1 []uuid.UUID) ([]AiAction, error) {
	rows, err := q.db.Query(ctx, listActionsByMessages, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AiAction
	for rows.Next() {
		var i AiAction
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.UserID,
			&i.Position,
			&i.Kind,
			&i.Payload,
			&i.Status,
			&i.Result,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setActionStatusFrom = `-- name: SetActionStatusFrom :one
UPDATE ai_actions
SET status = $3, result = COALESCE($4, result)
WHERE id = $1 AND user_id = $2 AND status = $5
RETURNING id, message_id, user_id, position, kind, payload, status, result, created_at
`

type SetActionStatusFromParams struct {
	ID       uuid.UUID `json:"id"`
	UserID   uuid.UUID `json:"user_id"`
	Status   string    `json:"status"`
	Result   []byte    `json:"result"`
	Status_2 string    `json:"status_2"`
}

func (q *Queries) SetActionStatusFrom(ctx context.Context, arg SetActionStatusFromParams) (AiAction, error) {
	row := q.db.QueryRow(ctx, setActionStatusFrom,
		arg.ID,
		arg.UserID,
		arg.Status,
		arg.Result,
		arg.Status_2,
	)
	var i AiAction
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.UserID,
		&i.Position,
		&i.Kind,
		&i.Payload,
		&i.Status,
		&i.Result,
		&i.CreatedAt,
	)
	return i, err
}
