// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ai_insights.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createInsight = `-- name: CreateInsight :one
INSERT INTO ai_insights (user_id, insight_date, kind, content, context_snapshot)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, insight_date, kind, content, context_snapshot, generated_at
`

type CreateInsightParams struct {
	UserID          uuid.UUID `json:"user_id"`
	InsightDate     time.Time `json:"insight_date"`
	Kind            string    `json:"kind"`
	Content         string    `json:"content"`
	ContextSnapshot []byte    `json:"context_snapshot"`
}

func (q *Queries) CreateInsight(ctx context.Context, arg CreateInsightParams) (AiInsight, error) {
	row := q.db.QueryRow(ctx, createInsight,
		arg.UserID,
		arg.InsightDate,
		arg.Kind,
		arg.Content,
		arg.ContextSnapshot,
	)
	var i AiInsight
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.InsightDate,
		&i.Kind,
		&i.Content,
		&i.ContextSnapshot,
		&i.GeneratedAt,
	)
	return i, err
}

const getInsight = `-- name: GetInsight :one
SELECT id, user_id, insight_date, kind, content, context_snapshot, generated_at FROM ai_insights
WHERE user_id = $1 AND insight_date = $2 AND kind = $3
`

type GetInsightParams struct {
	UserID      uuid.UUID `json:"user_id"`
	InsightDate time.Time `json:"insight_date"`
	Kind        string    `json:"kind"`
}

func (q *Queries) GetInsight(ctx context.Context, arg GetInsightParams) (AiInsight, error) {
	row := q.db.QueryRow(ctx, getInsight, arg.UserID, arg.InsightDate, arg.Kind)
	var i AiInsight
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.InsightDate,
		&i.Kind,
		&i.Content,
		&i.ContextSnapshot,
		&i.GeneratedAt,
	)
	return i, err
}
