// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ai_messages.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO ai_messages (user_id, role, content)
VALUES ($1, $2, $3)
RETURNING id, user_id, role, content, created_at
`

type CreateMessageParams struct {
	UserID  uuid.UUID `json:"user_id"`
	Role    string    `json:"role"`
	Content string    `json:"content"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (AiMessage, error) {
	row := q.db.QueryRow(ctx, createMessage, arg.UserID, arg.Role, arg.Content)
	var i AiMessage
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Role,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const listMessages = `-- name: ListMessages :many
SELECT id, user_id, role, content, created_at FROM ai_messages
WHERE user_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListMessages(ctx context.Context, userID uuid.UUID) ([]AiMessage, error) {
	rows, err := q.db.Query(ctx, listMessages, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AiMessage
	for rows.Next() {
		var i AiMessage
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Role,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
