// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ai_messages.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO ai_messages (user_id, thread_id, role, content)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, role, content, created_at, thread_id
`

type CreateMessageParams struct {
	UserID   uuid.UUID `json:"user_id"`
	ThreadID uuid.UUID `json:"thread_id"`
	Role     string    `json:"role"`
	Content  string    `json:"content"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (AiMessage, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.UserID,
		arg.ThreadID,
		arg.Role,
		arg.Content,
	)
	var i AiMessage
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Role,
		&i.Content,
		&i.CreatedAt,
		&i.ThreadID,
	)
	return i, err
}

const listThreadMessages = `-- name: ListThreadMessages :many
SELECT id, user_id, role, content, created_at, thread_id FROM ai_messages
WHERE thread_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListThreadMessages(ctx context.Context, threadID uuid.UUID) ([]AiMessage, error) {
	rows, err := q.db.Query(ctx, listThreadMessages, threadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AiMessage
	for rows.Next() {
		var i AiMessage
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Role,
			&i.Content,
			&i.CreatedAt,
			&i.ThreadID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
