// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ai_messages.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO ai_messages (user_id, role, content)
VALUES ($1, $2, $3)
RETURNING id, user_id, role, content, created_at, action_kind, action_payload, action_status
`

type CreateMessageParams struct {
	UserID  uuid.UUID `json:"user_id"`
	Role    string    `json:"role"`
	Content string    `json:"content"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (AiMessage, error) {
	row := q.db.QueryRow(ctx, createMessage, arg.UserID, arg.Role, arg.Content)
	var i AiMessage
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Role,
		&i.Content,
		&i.CreatedAt,
		&i.ActionKind,
		&i.ActionPayload,
		&i.ActionStatus,
	)
	return i, err
}

const createMessageWithAction = `-- name: CreateMessageWithAction :one
INSERT INTO ai_messages (user_id, role, content, action_kind, action_payload, action_status)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, role, content, created_at, action_kind, action_payload, action_status
`

type CreateMessageWithActionParams struct {
	UserID        uuid.UUID `json:"user_id"`
	Role          string    `json:"role"`
	Content       string    `json:"content"`
	ActionKind    *string   `json:"action_kind"`
	ActionPayload []byte    `json:"action_payload"`
	ActionStatus  *string   `json:"action_status"`
}

func (q *Queries) CreateMessageWithAction(ctx context.Context, arg CreateMessageWithActionParams) (AiMessage, error) {
	row := q.db.QueryRow(ctx, createMessageWithAction,
		arg.UserID,
		arg.Role,
		arg.Content,
		arg.ActionKind,
		arg.ActionPayload,
		arg.ActionStatus,
	)
	var i AiMessage
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Role,
		&i.Content,
		&i.CreatedAt,
		&i.ActionKind,
		&i.ActionPayload,
		&i.ActionStatus,
	)
	return i, err
}

const getMessageForAction = `-- name: GetMessageForAction :one
SELECT id, user_id, role, content, created_at, action_kind, action_payload, action_status FROM ai_messages
WHERE id = $1 AND user_id = $2
`

type GetMessageForActionParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetMessageForAction(ctx context.Context, arg GetMessageForActionParams) (AiMessage, error) {
	row := q.db.QueryRow(ctx, getMessageForAction, arg.ID, arg.UserID)
	var i AiMessage
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Role,
		&i.Content,
		&i.CreatedAt,
		&i.ActionKind,
		&i.ActionPayload,
		&i.ActionStatus,
	)
	return i, err
}

const listMessages = `-- name: ListMessages :many
SELECT id, user_id, role, content, created_at, action_kind, action_payload, action_status FROM ai_messages
WHERE user_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListMessages(ctx context.Context, userID uuid.UUID) ([]AiMessage, error) {
	rows, err := q.db.Query(ctx, listMessages, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AiMessage
	for rows.Next() {
		var i AiMessage
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Role,
			&i.Content,
			&i.CreatedAt,
			&i.ActionKind,
			&i.ActionPayload,
			&i.ActionStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setActionStatus = `-- name: SetActionStatus :one
UPDATE ai_messages
SET action_status = $3
WHERE id = $1 AND user_id = $2 AND action_status = 'proposed'
RETURNING id, user_id, role, content, created_at, action_kind, action_payload, action_status
`

type SetActionStatusParams struct {
	ID           uuid.UUID `json:"id"`
	UserID       uuid.UUID `json:"user_id"`
	ActionStatus *string   `json:"action_status"`
}

func (q *Queries) SetActionStatus(ctx context.Context, arg SetActionStatusParams) (AiMessage, error) {
	row := q.db.QueryRow(ctx, setActionStatus, arg.ID, arg.UserID, arg.ActionStatus)
	var i AiMessage
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Role,
		&i.Content,
		&i.CreatedAt,
		&i.ActionKind,
		&i.ActionPayload,
		&i.ActionStatus,
	)
	return i, err
}
