// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ai_search.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const searchMessages = `-- name: SearchMessages :many
SELECT m.id, m.thread_id, m.role, m.content, m.created_at,
       t.title AS thread_title
FROM ai_messages m
JOIN ai_threads t ON t.id = m.thread_id
WHERE m.user_id = $1
  AND unaccent(lower(m.content)) LIKE '%' || unaccent(lower($2::text)) || '%'
ORDER BY m.created_at DESC
LIMIT $3
`

type SearchMessagesParams struct {
	UserID uuid.UUID `json:"user_id"`
	Term   string    `json:"term"`
	Lim    int32     `json:"lim"`
}

type SearchMessagesRow struct {
	ID          uuid.UUID `json:"id"`
	ThreadID    uuid.UUID `json:"thread_id"`
	Role        string    `json:"role"`
	Content     string    `json:"content"`
	CreatedAt   time.Time `json:"created_at"`
	ThreadTitle string    `json:"thread_title"`
}

func (q *Queries) SearchMessages(ctx context.Context, arg SearchMessagesParams) ([]SearchMessagesRow, error) {
	rows, err := q.db.Query(ctx, searchMessages, arg.UserID, arg.Term, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchMessagesRow
	for rows.Next() {
		var i SearchMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.ThreadID,
			&i.Role,
			&i.Content,
			&i.CreatedAt,
			&i.ThreadTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchThreadsByTitle = `-- name: SearchThreadsByTitle :many
SELECT t.id, t.title, t.updated_at,
       COALESCE(lm.content, '') AS preview
FROM ai_threads t
LEFT JOIN LATERAL (
    SELECT content FROM ai_messages m
    WHERE m.thread_id = t.id
    ORDER BY m.created_at DESC
    LIMIT 1
) lm ON true
WHERE t.user_id = $1
  AND unaccent(lower(t.title)) LIKE '%' || unaccent(lower($2::text)) || '%'
ORDER BY t.updated_at DESC
LIMIT $3
`

type SearchThreadsByTitleParams struct {
	UserID uuid.UUID `json:"user_id"`
	Term   string    `json:"term"`
	Lim    int32     `json:"lim"`
}

type SearchThreadsByTitleRow struct {
	ID        uuid.UUID `json:"id"`
	Title     string    `json:"title"`
	UpdatedAt time.Time `json:"updated_at"`
	Preview   string    `json:"preview"`
}

func (q *Queries) SearchThreadsByTitle(ctx context.Context, arg SearchThreadsByTitleParams) ([]SearchThreadsByTitleRow, error) {
	rows, err := q.db.Query(ctx, searchThreadsByTitle, arg.UserID, arg.Term, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchThreadsByTitleRow
	for rows.Next() {
		var i SearchThreadsByTitleRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.UpdatedAt,
			&i.Preview,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
