// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ai_threads.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createThread = `-- name: CreateThread :one
INSERT INTO ai_threads (user_id, title)
VALUES ($1, $2)
RETURNING id, user_id, title, created_at, updated_at
`

type CreateThreadParams struct {
	UserID uuid.UUID `json:"user_id"`
	Title  string    `json:"title"`
}

func (q *Queries) CreateThread(ctx context.Context, arg CreateThreadParams) (AiThread, error) {
	row := q.db.QueryRow(ctx, createThread, arg.UserID, arg.Title)
	var i AiThread
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteThread = `-- name: DeleteThread :execrows
DELETE FROM ai_threads
WHERE id = $1 AND user_id = $2
`

type DeleteThreadParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteThread(ctx context.Context, arg DeleteThreadParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteThread, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getThread = `-- name: GetThread :one
SELECT id, user_id, title, created_at, updated_at FROM ai_threads
WHERE id = $1 AND user_id = $2
`

type GetThreadParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetThread(ctx context.Context, arg GetThreadParams) (AiThread, error) {
	row := q.db.QueryRow(ctx, getThread, arg.ID, arg.UserID)
	var i AiThread
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listThreads = `-- name: ListThreads :many
SELECT t.id, t.user_id, t.title, t.created_at, t.updated_at,
       COALESCE(lm.content, '') AS preview
FROM ai_threads t
LEFT JOIN LATERAL (
    SELECT content FROM ai_messages m
    WHERE m.thread_id = t.id
    ORDER BY m.created_at DESC
    LIMIT 1
) lm ON true
WHERE t.user_id = $1
ORDER BY t.updated_at DESC
`

type ListThreadsRow struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	Title     string    `json:"title"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	Preview   string    `json:"preview"`
}

func (q *Queries) ListThreads(ctx context.Context, userID uuid.UUID) ([]ListThreadsRow, error) {
	rows, err := q.db.Query(ctx, listThreads, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListThreadsRow
	for rows.Next() {
		var i ListThreadsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Preview,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameThread = `-- name: RenameThread :one
UPDATE ai_threads SET title = $3
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, title, created_at, updated_at
`

type RenameThreadParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
	Title  string    `json:"title"`
}

func (q *Queries) RenameThread(ctx context.Context, arg RenameThreadParams) (AiThread, error) {
	row := q.db.QueryRow(ctx, renameThread, arg.ID, arg.UserID, arg.Title)
	var i AiThread
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const touchThread = `-- name: TouchThread :exec
UPDATE ai_threads SET updated_at = now()
WHERE id = $1
`

func (q *Queries) TouchThread(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchThread, id)
	return err
}
