// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: check_ins.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteCheckIn = `-- name: DeleteCheckIn :execrows
DELETE FROM check_ins
WHERE user_id = $1 AND date = $2
`

type DeleteCheckInParams struct {
	UserID uuid.UUID `json:"user_id"`
	Date   time.Time `json:"date"`
}

func (q *Queries) DeleteCheckIn(ctx context.Context, arg DeleteCheckInParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCheckIn, arg.UserID, arg.Date)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCheckInByDate = `-- name: GetCheckInByDate :one
SELECT id, user_id, date, mood, energy, discipline, note, created_at, updated_at FROM check_ins
WHERE user_id = $1 AND date = $2
`

type GetCheckInByDateParams struct {
	UserID uuid.UUID `json:"user_id"`
	Date   time.Time `json:"date"`
}

func (q *Queries) GetCheckInByDate(ctx context.Context, arg GetCheckInByDateParams) (CheckIn, error) {
	row := q.db.QueryRow(ctx, getCheckInByDate, arg.UserID, arg.Date)
	var i CheckIn
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Date,
		&i.Mood,
		&i.Energy,
		&i.Discipline,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCheckIns = `-- name: ListCheckIns :many
SELECT id, user_id, date, mood, energy, discipline, note, created_at, updated_at FROM check_ins
WHERE user_id = $1
ORDER BY date DESC
LIMIT $2
`

type ListCheckInsParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
}

func (q *Queries) ListCheckIns(ctx context.Context, arg ListCheckInsParams) ([]CheckIn, error) {
	rows, err := q.db.Query(ctx, listCheckIns, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CheckIn
	for rows.Next() {
		var i CheckIn
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Date,
			&i.Mood,
			&i.Energy,
			&i.Discipline,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCheckIn = `-- name: UpsertCheckIn :one
INSERT INTO check_ins (user_id, date, mood, energy, discipline, note)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (user_id, date)
DO UPDATE SET
    mood = EXCLUDED.mood,
    energy = EXCLUDED.energy,
    discipline = EXCLUDED.discipline,
    note = EXCLUDED.note,
    updated_at = now()
RETURNING id, user_id, date, mood, energy, discipline, note, created_at, updated_at
`

type UpsertCheckInParams struct {
	UserID     uuid.UUID `json:"user_id"`
	Date       time.Time `json:"date"`
	Mood       int32     `json:"mood"`
	Energy     int32     `json:"energy"`
	Discipline int32     `json:"discipline"`
	Note       string    `json:"note"`
}

func (q *Queries) UpsertCheckIn(ctx context.Context, arg UpsertCheckInParams) (CheckIn, error) {
	row := q.db.QueryRow(ctx, upsertCheckIn,
		arg.UserID,
		arg.Date,
		arg.Mood,
		arg.Energy,
		arg.Discipline,
		arg.Note,
	)
	var i CheckIn
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Date,
		&i.Mood,
		&i.Energy,
		&i.Discipline,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
