// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: commitments.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createCommitment = `-- name: CreateCommitment :one
INSERT INTO commitments (user_id, target_date, text, position)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, target_date, text, done, position, created_at, updated_at
`

type CreateCommitmentParams struct {
	UserID     uuid.UUID `json:"user_id"`
	TargetDate time.Time `json:"target_date"`
	Text       string    `json:"text"`
	Position   int32     `json:"position"`
}

func (q *Queries) CreateCommitment(ctx context.Context, arg CreateCommitmentParams) (Commitment, error) {
	row := q.db.QueryRow(ctx, createCommitment,
		arg.UserID,
		arg.TargetDate,
		arg.Text,
		arg.Position,
	)
	var i Commitment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TargetDate,
		&i.Text,
		&i.Done,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCommitmentsForDate = `-- name: DeleteCommitmentsForDate :execrows
DELETE FROM commitments WHERE user_id = $1 AND target_date = $2
`

type DeleteCommitmentsForDateParams struct {
	UserID     uuid.UUID `json:"user_id"`
	TargetDate time.Time `json:"target_date"`
}

func (q *Queries) DeleteCommitmentsForDate(ctx context.Context, arg DeleteCommitmentsForDateParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCommitmentsForDate, arg.UserID, arg.TargetDate)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listCommitmentsByTarget = `-- name: ListCommitmentsByTarget :many
SELECT id, user_id, target_date, text, done, position, created_at, updated_at FROM commitments
WHERE user_id = $1 AND target_date = $2
ORDER BY position
`

type ListCommitmentsByTargetParams struct {
	UserID     uuid.UUID `json:"user_id"`
	TargetDate time.Time `json:"target_date"`
}

func (q *Queries) ListCommitmentsByTarget(ctx context.Context, arg ListCommitmentsByTargetParams) ([]Commitment, error) {
	rows, err := q.db.Query(ctx, listCommitmentsByTarget, arg.UserID, arg.TargetDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Commitment
	for rows.Next() {
		var i Commitment
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TargetDate,
			&i.Text,
			&i.Done,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingCommitments = `-- name: ListPendingCommitments :many
SELECT id, user_id, target_date, text, done, position, created_at, updated_at FROM commitments
WHERE user_id = $1 AND done = false AND target_date <= $2
ORDER BY target_date ASC, position ASC
`

type ListPendingCommitmentsParams struct {
	UserID     uuid.UUID `json:"user_id"`
	TargetDate time.Time `json:"target_date"`
}

func (q *Queries) ListPendingCommitments(ctx context.Context, arg ListPendingCommitmentsParams) ([]Commitment, error) {
	rows, err := q.db.Query(ctx, listPendingCommitments, arg.UserID, arg.TargetDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Commitment
	for rows.Next() {
		var i Commitment
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TargetDate,
			&i.Text,
			&i.Done,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentCommitments = `-- name: ListRecentCommitments :many
SELECT id, user_id, target_date, text, done, position, created_at, updated_at FROM commitments
WHERE user_id = $1 AND target_date >= $2
ORDER BY target_date DESC, position
`

type ListRecentCommitmentsParams struct {
	UserID     uuid.UUID `json:"user_id"`
	TargetDate time.Time `json:"target_date"`
}

func (q *Queries) ListRecentCommitments(ctx context.Context, arg ListRecentCommitmentsParams) ([]Commitment, error) {
	rows, err := q.db.Query(ctx, listRecentCommitments, arg.UserID, arg.TargetDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Commitment
	for rows.Next() {
		var i Commitment
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TargetDate,
			&i.Text,
			&i.Done,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toggleCommitment = `-- name: ToggleCommitment :one
UPDATE commitments
SET done = NOT done, updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, target_date, text, done, position, created_at, updated_at
`

type ToggleCommitmentParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) ToggleCommitment(ctx context.Context, arg ToggleCommitmentParams) (Commitment, error) {
	row := q.db.QueryRow(ctx, toggleCommitment, arg.ID, arg.UserID)
	var i Commitment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TargetDate,
		&i.Text,
		&i.Done,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
