// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fitness_profiles.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getFitnessProfile = `-- name: GetFitnessProfile :one
SELECT user_id, birthdate, sex, height_cm, weight_grams, objective, location, level, weekly_days, equipment, limitations, updated_at FROM fitness_profiles WHERE user_id = $1
`

func (q *Queries) GetFitnessProfile(ctx context.Context, userID uuid.UUID) (FitnessProfile, error) {
	row := q.db.QueryRow(ctx, getFitnessProfile, userID)
	var i FitnessProfile
	err := row.Scan(
		&i.UserID,
		&i.Birthdate,
		&i.Sex,
		&i.HeightCm,
		&i.WeightGrams,
		&i.Objective,
		&i.Location,
		&i.Level,
		&i.WeeklyDays,
		&i.Equipment,
		&i.Limitations,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertFitnessProfile = `-- name: UpsertFitnessProfile :one
INSERT INTO fitness_profiles (
    user_id, birthdate, sex, height_cm, weight_grams, objective,
    location, level, weekly_days, equipment, limitations, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11, now()
)
ON CONFLICT (user_id) DO UPDATE SET
    birthdate    = EXCLUDED.birthdate,
    sex          = EXCLUDED.sex,
    height_cm    = EXCLUDED.height_cm,
    weight_grams = EXCLUDED.weight_grams,
    objective    = EXCLUDED.objective,
    location     = EXCLUDED.location,
    level        = EXCLUDED.level,
    weekly_days  = EXCLUDED.weekly_days,
    equipment    = EXCLUDED.equipment,
    limitations  = EXCLUDED.limitations,
    updated_at   = now()
RETURNING user_id, birthdate, sex, height_cm, weight_grams, objective, location, level, weekly_days, equipment, limitations, updated_at
`

type UpsertFitnessProfileParams struct {
	UserID      uuid.UUID  `json:"user_id"`
	Birthdate   *time.Time `json:"birthdate"`
	Sex         *string    `json:"sex"`
	HeightCm    *int32     `json:"height_cm"`
	WeightGrams *int32     `json:"weight_grams"`
	Objective   *string    `json:"objective"`
	Location    *string    `json:"location"`
	Level       *string    `json:"level"`
	WeeklyDays  *int32     `json:"weekly_days"`
	Equipment   []string   `json:"equipment"`
	Limitations string     `json:"limitations"`
}

func (q *Queries) UpsertFitnessProfile(ctx context.Context, arg UpsertFitnessProfileParams) (FitnessProfile, error) {
	row := q.db.QueryRow(ctx, upsertFitnessProfile,
		arg.UserID,
		arg.Birthdate,
		arg.Sex,
		arg.HeightCm,
		arg.WeightGrams,
		arg.Objective,
		arg.Location,
		arg.Level,
		arg.WeeklyDays,
		arg.Equipment,
		arg.Limitations,
	)
	var i FitnessProfile
	err := row.Scan(
		&i.UserID,
		&i.Birthdate,
		&i.Sex,
		&i.HeightCm,
		&i.WeightGrams,
		&i.Objective,
		&i.Location,
		&i.Level,
		&i.WeeklyDays,
		&i.Equipment,
		&i.Limitations,
		&i.UpdatedAt,
	)
	return i, err
}
