// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: goals.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createGoal = `-- name: CreateGoal :one
INSERT INTO goals (user_id, title, dimension, deadline)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, title, dimension, status, progress, deadline, created_at
`

type CreateGoalParams struct {
	UserID    uuid.UUID  `json:"user_id"`
	Title     string     `json:"title"`
	Dimension string     `json:"dimension"`
	Deadline  *time.Time `json:"deadline"`
}

func (q *Queries) CreateGoal(ctx context.Context, arg CreateGoalParams) (Goal, error) {
	row := q.db.QueryRow(ctx, createGoal,
		arg.UserID,
		arg.Title,
		arg.Dimension,
		arg.Deadline,
	)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Dimension,
		&i.Status,
		&i.Progress,
		&i.Deadline,
		&i.CreatedAt,
	)
	return i, err
}

const deleteGoal = `-- name: DeleteGoal :execrows
DELETE FROM goals
WHERE id = $1 AND user_id = $2
`

type DeleteGoalParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteGoal(ctx context.Context, arg DeleteGoalParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteGoal, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getGoal = `-- name: GetGoal :one
SELECT id, user_id, title, dimension, status, progress, deadline, created_at FROM goals
WHERE id = $1 AND user_id = $2
`

type GetGoalParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetGoal(ctx context.Context, arg GetGoalParams) (Goal, error) {
	row := q.db.QueryRow(ctx, getGoal, arg.ID, arg.UserID)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Dimension,
		&i.Status,
		&i.Progress,
		&i.Deadline,
		&i.CreatedAt,
	)
	return i, err
}

const listGoals = `-- name: ListGoals :many
SELECT id, user_id, title, dimension, status, progress, deadline, created_at FROM goals
WHERE user_id = $1 AND status = $2
ORDER BY created_at DESC
`

type ListGoalsParams struct {
	UserID uuid.UUID `json:"user_id"`
	Status string    `json:"status"`
}

func (q *Queries) ListGoals(ctx context.Context, arg ListGoalsParams) ([]Goal, error) {
	rows, err := q.db.Query(ctx, listGoals, arg.UserID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Goal
	for rows.Next() {
		var i Goal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Dimension,
			&i.Status,
			&i.Progress,
			&i.Deadline,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGoal = `-- name: UpdateGoal :one
UPDATE goals SET
    title     = COALESCE($1, title),
    dimension = COALESCE($2, dimension),
    status    = COALESCE($3, status),
    progress  = COALESCE($4, progress),
    deadline  = CASE WHEN $5::bool
                     THEN $6
                     ELSE deadline END
WHERE id = $7 AND user_id = $8
RETURNING id, user_id, title, dimension, status, progress, deadline, created_at
`

type UpdateGoalParams struct {
	Title       *string    `json:"title"`
	Dimension   *string    `json:"dimension"`
	Status      *string    `json:"status"`
	Progress    *int32     `json:"progress"`
	SetDeadline bool       `json:"set_deadline"`
	Deadline    *time.Time `json:"deadline"`
	ID          uuid.UUID  `json:"id"`
	UserID      uuid.UUID  `json:"user_id"`
}

func (q *Queries) UpdateGoal(ctx context.Context, arg UpdateGoalParams) (Goal, error) {
	row := q.db.QueryRow(ctx, updateGoal,
		arg.Title,
		arg.Dimension,
		arg.Status,
		arg.Progress,
		arg.SetDeadline,
		arg.Deadline,
		arg.ID,
		arg.UserID,
	)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Dimension,
		&i.Status,
		&i.Progress,
		&i.Deadline,
		&i.CreatedAt,
	)
	return i, err
}
