// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: goal_notes.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createGoalNote = `-- name: CreateGoalNote :one
INSERT INTO goal_notes (goal_id, user_id, note_date, body)
SELECT $1, $2, $3, $4
WHERE EXISTS (SELECT 1 FROM goals WHERE id = $1 AND user_id = $2)
RETURNING id, goal_id, user_id, note_date, body, created_at
`

type CreateGoalNoteParams struct {
	GoalID   uuid.UUID `json:"goal_id"`
	UserID   uuid.UUID `json:"user_id"`
	NoteDate time.Time `json:"note_date"`
	Body     string    `json:"body"`
}

func (q *Queries) CreateGoalNote(ctx context.Context, arg CreateGoalNoteParams) (GoalNote, error) {
	row := q.db.QueryRow(ctx, createGoalNote,
		arg.GoalID,
		arg.UserID,
		arg.NoteDate,
		arg.Body,
	)
	var i GoalNote
	err := row.Scan(
		&i.ID,
		&i.GoalID,
		&i.UserID,
		&i.NoteDate,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const deleteGoalNote = `-- name: DeleteGoalNote :execrows
DELETE FROM goal_notes WHERE id = $1 AND user_id = $2
`

type DeleteGoalNoteParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteGoalNote(ctx context.Context, arg DeleteGoalNoteParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteGoalNote, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listGoalNotes = `-- name: ListGoalNotes :many
SELECT n.id, n.goal_id, n.user_id, n.note_date, n.body, n.created_at FROM goal_notes n
JOIN goals g ON g.id = n.goal_id
WHERE n.goal_id = $1 AND g.user_id = $2
ORDER BY n.note_date DESC, n.created_at DESC
`

type ListGoalNotesParams struct {
	GoalID uuid.UUID `json:"goal_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) ListGoalNotes(ctx context.Context, arg ListGoalNotesParams) ([]GoalNote, error) {
	rows, err := q.db.Query(ctx, listGoalNotes, arg.GoalID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GoalNote
	for rows.Next() {
		var i GoalNote
		if err := rows.Scan(
			&i.ID,
			&i.GoalID,
			&i.UserID,
			&i.NoteDate,
			&i.Body,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
