// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: habits.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const archiveHabit = `-- name: ArchiveHabit :one
UPDATE habits
SET archived_at = now()
WHERE id = $1 AND user_id = $2 AND archived_at IS NULL
RETURNING id, user_id, name, target_days, archived_at, created_at
`

type ArchiveHabitParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) ArchiveHabit(ctx context.Context, arg ArchiveHabitParams) (Habit, error) {
	row := q.db.QueryRow(ctx, archiveHabit, arg.ID, arg.UserID)
	var i Habit
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TargetDays,
		&i.ArchivedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createHabit = `-- name: CreateHabit :one
INSERT INTO habits (user_id, name, target_days)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, lower(name)) WHERE archived_at IS NULL
DO UPDATE SET name = habits.name
RETURNING id, user_id, name, target_days, archived_at, created_at
`

type CreateHabitParams struct {
	UserID     uuid.UUID `json:"user_id"`
	Name       string    `json:"name"`
	TargetDays *int32    `json:"target_days"`
}

// Idempotente por (user_id, lower(name)) entre hábitos ACTIVOS: si ya existe
// uno activo con ese nombre, devuelve el actual (no toca target_days).
func (q *Queries) CreateHabit(ctx context.Context, arg CreateHabitParams) (Habit, error) {
	row := q.db.QueryRow(ctx, createHabit, arg.UserID, arg.Name, arg.TargetDays)
	var i Habit
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TargetDays,
		&i.ArchivedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteHabit = `-- name: DeleteHabit :execrows
DELETE FROM habits
WHERE id = $1 AND user_id = $2
`

type DeleteHabitParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteHabit(ctx context.Context, arg DeleteHabitParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteHabit, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteHabitLog = `-- name: DeleteHabitLog :exec
DELETE FROM habit_logs
WHERE habit_id = $1 AND day = $2
`

type DeleteHabitLogParams struct {
	HabitID uuid.UUID `json:"habit_id"`
	Day     time.Time `json:"day"`
}

func (q *Queries) DeleteHabitLog(ctx context.Context, arg DeleteHabitLogParams) error {
	_, err := q.db.Exec(ctx, deleteHabitLog, arg.HabitID, arg.Day)
	return err
}

const getHabit = `-- name: GetHabit :one
SELECT id, user_id, name, target_days, archived_at, created_at FROM habits
WHERE id = $1 AND user_id = $2
`

type GetHabitParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetHabit(ctx context.Context, arg GetHabitParams) (Habit, error) {
	row := q.db.QueryRow(ctx, getHabit, arg.ID, arg.UserID)
	var i Habit
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TargetDays,
		&i.ArchivedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listArchivedHabits = `-- name: ListArchivedHabits :many
SELECT id, user_id, name, target_days, archived_at, created_at FROM habits
WHERE user_id = $1 AND archived_at IS NOT NULL
ORDER BY archived_at DESC
`

func (q *Queries) ListArchivedHabits(ctx context.Context, userID uuid.UUID) ([]Habit, error) {
	rows, err := q.db.Query(ctx, listArchivedHabits, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Habit
	for rows.Next() {
		var i Habit
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.TargetDays,
			&i.ArchivedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHabits = `-- name: ListHabits :many
SELECT id, user_id, name, target_days, archived_at, created_at FROM habits
WHERE user_id = $1 AND archived_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListHabits(ctx context.Context, userID uuid.UUID) ([]Habit, error) {
	rows, err := q.db.Query(ctx, listHabits, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Habit
	for rows.Next() {
		var i Habit
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.TargetDays,
			&i.ArchivedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLogsByHabitIDs = `-- name: ListLogsByHabitIDs :many
SELECT habit_id, day FROM habit_logs
WHERE habit_id = ANY($1::uuid[])
ORDER BY day ASC
`

type ListLogsByHabitIDsRow struct {
	HabitID uuid.UUID `json:"habit_id"`
	Day     time.Time `json:"day"`
}

func (q *Queries) ListLogsByHabitIDs(ctx context.Context, habitIds []uuid.UUID) ([]ListLogsByHabitIDsRow, error) {
	rows, err := q.db.Query(ctx, listLogsByHabitIDs, habitIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLogsByHabitIDsRow
	for rows.Next() {
		var i ListLogsByHabitIDsRow
		if err := rows.Scan(&i.HabitID, &i.Day); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertHabitLog = `-- name: UpsertHabitLog :exec
INSERT INTO habit_logs (habit_id, day)
VALUES ($1, $2)
ON CONFLICT (habit_id, day) DO NOTHING
`

type UpsertHabitLogParams struct {
	HabitID uuid.UUID `json:"habit_id"`
	Day     time.Time `json:"day"`
}

func (q *Queries) UpsertHabitLog(ctx context.Context, arg UpsertHabitLogParams) error {
	_, err := q.db.Exec(ctx, upsertHabitLog, arg.HabitID, arg.Day)
	return err
}
