// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"time"

	"github.com/google/uuid"
)

type AiInsight struct {
	ID              uuid.UUID `json:"id"`
	UserID          uuid.UUID `json:"user_id"`
	InsightDate     time.Time `json:"insight_date"`
	Kind            string    `json:"kind"`
	Content         string    `json:"content"`
	ContextSnapshot []byte    `json:"context_snapshot"`
	GeneratedAt     time.Time `json:"generated_at"`
}

type CheckIn struct {
	ID         uuid.UUID `json:"id"`
	UserID     uuid.UUID `json:"user_id"`
	Date       time.Time `json:"date"`
	Mood       int32     `json:"mood"`
	Energy     int32     `json:"energy"`
	Discipline int32     `json:"discipline"`
	Note       string    `json:"note"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type Exercise struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

type Goal struct {
	ID        uuid.UUID  `json:"id"`
	UserID    uuid.UUID  `json:"user_id"`
	Title     string     `json:"title"`
	Dimension string     `json:"dimension"`
	Status    string     `json:"status"`
	Progress  int32      `json:"progress"`
	Deadline  *time.Time `json:"deadline"`
	CreatedAt time.Time  `json:"created_at"`
}

type Habit struct {
	ID         uuid.UUID  `json:"id"`
	UserID     uuid.UUID  `json:"user_id"`
	Name       string     `json:"name"`
	TargetDays *int32     `json:"target_days"`
	ArchivedAt *time.Time `json:"archived_at"`
	CreatedAt  time.Time  `json:"created_at"`
}

type HabitLog struct {
	ID        uuid.UUID `json:"id"`
	HabitID   uuid.UUID `json:"habit_id"`
	Day       time.Time `json:"day"`
	CreatedAt time.Time `json:"created_at"`
}

type Transaction struct {
	ID         uuid.UUID `json:"id"`
	UserID     uuid.UUID `json:"user_id"`
	Type       string    `json:"type"`
	Amount     int64     `json:"amount"`
	OccurredOn time.Time `json:"occurred_on"`
	Cycle      time.Time `json:"cycle"`
	Category   string    `json:"category"`
	Remark     string    `json:"remark"`
	Source     string    `json:"source"`
	ExternalID *string   `json:"external_id"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type User struct {
	ID           uuid.UUID `json:"id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	Name         string    `json:"name"`
	CreatedAt    time.Time `json:"created_at"`
}

type Workout struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	Date      time.Time `json:"date"`
	Type      string    `json:"type"`
	Note      string    `json:"note"`
	CreatedAt time.Time `json:"created_at"`
}

type WorkoutSet struct {
	ID          uuid.UUID `json:"id"`
	WorkoutID   uuid.UUID `json:"workout_id"`
	ExerciseID  uuid.UUID `json:"exercise_id"`
	Position    int32     `json:"position"`
	Reps        *int32    `json:"reps"`
	WeightGrams *int32    `json:"weight_grams"`
	CreatedAt   time.Time `json:"created_at"`
}
