// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: training_suggestions.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const getTrainingSuggestion = `-- name: GetTrainingSuggestion :one
SELECT user_id, focus, content, created_at FROM training_suggestions WHERE user_id = $1
`

func (q *Queries) GetTrainingSuggestion(ctx context.Context, userID uuid.UUID) (TrainingSuggestion, error) {
	row := q.db.QueryRow(ctx, getTrainingSuggestion, userID)
	var i TrainingSuggestion
	err := row.Scan(
		&i.UserID,
		&i.Focus,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const upsertTrainingSuggestion = `-- name: UpsertTrainingSuggestion :one
INSERT INTO training_suggestions (user_id, focus, content, created_at)
VALUES ($1, $2, $3, now())
ON CONFLICT (user_id) DO UPDATE SET
    focus      = EXCLUDED.focus,
    content    = EXCLUDED.content,
    created_at = now()
RETURNING user_id, focus, content, created_at
`

type UpsertTrainingSuggestionParams struct {
	UserID  uuid.UUID `json:"user_id"`
	Focus   string    `json:"focus"`
	Content string    `json:"content"`
}

func (q *Queries) UpsertTrainingSuggestion(ctx context.Context, arg UpsertTrainingSuggestionParams) (TrainingSuggestion, error) {
	row := q.db.QueryRow(ctx, upsertTrainingSuggestion, arg.UserID, arg.Focus, arg.Content)
	var i TrainingSuggestion
	err := row.Scan(
		&i.UserID,
		&i.Focus,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}
