// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: training_adjustments.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const getTrainingAdjustment = `-- name: GetTrainingAdjustment :one
SELECT user_id, scope, content, created_at FROM training_adjustments WHERE user_id = $1
`

func (q *Queries) GetTrainingAdjustment(ctx context.Context, userID uuid.UUID) (TrainingAdjustment, error) {
	row := q.db.QueryRow(ctx, getTrainingAdjustment, userID)
	var i TrainingAdjustment
	err := row.Scan(
		&i.UserID,
		&i.Scope,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const upsertTrainingAdjustment = `-- name: UpsertTrainingAdjustment :one
INSERT INTO training_adjustments (user_id, scope, content, created_at)
VALUES ($1, $2, $3, now())
ON CONFLICT (user_id) DO UPDATE SET
    scope      = EXCLUDED.scope,
    content    = EXCLUDED.content,
    created_at = now()
RETURNING user_id, scope, content, created_at
`

type UpsertTrainingAdjustmentParams struct {
	UserID  uuid.UUID `json:"user_id"`
	Scope   string    `json:"scope"`
	Content string    `json:"content"`
}

func (q *Queries) UpsertTrainingAdjustment(ctx context.Context, arg UpsertTrainingAdjustmentParams) (TrainingAdjustment, error) {
	row := q.db.QueryRow(ctx, upsertTrainingAdjustment, arg.UserID, arg.Scope, arg.Content)
	var i TrainingAdjustment
	err := row.Scan(
		&i.UserID,
		&i.Scope,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}
