// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: training.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createWorkout = `-- name: CreateWorkout :one
INSERT INTO workouts (user_id, date, type, note)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, date, type, note, created_at
`

type CreateWorkoutParams struct {
	UserID uuid.UUID `json:"user_id"`
	Date   time.Time `json:"date"`
	Type   string    `json:"type"`
	Note   string    `json:"note"`
}

func (q *Queries) CreateWorkout(ctx context.Context, arg CreateWorkoutParams) (Workout, error) {
	row := q.db.QueryRow(ctx, createWorkout,
		arg.UserID,
		arg.Date,
		arg.Type,
		arg.Note,
	)
	var i Workout
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Date,
		&i.Type,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const createWorkoutSet = `-- name: CreateWorkoutSet :one
INSERT INTO workout_sets (workout_id, exercise_id, position, reps, weight_grams, note)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, workout_id, exercise_id, position, reps, weight_grams, created_at, note
`

type CreateWorkoutSetParams struct {
	WorkoutID   uuid.UUID `json:"workout_id"`
	ExerciseID  uuid.UUID `json:"exercise_id"`
	Position    int32     `json:"position"`
	Reps        *int32    `json:"reps"`
	WeightGrams *int32    `json:"weight_grams"`
	Note        string    `json:"note"`
}

func (q *Queries) CreateWorkoutSet(ctx context.Context, arg CreateWorkoutSetParams) (WorkoutSet, error) {
	row := q.db.QueryRow(ctx, createWorkoutSet,
		arg.WorkoutID,
		arg.ExerciseID,
		arg.Position,
		arg.Reps,
		arg.WeightGrams,
		arg.Note,
	)
	var i WorkoutSet
	err := row.Scan(
		&i.ID,
		&i.WorkoutID,
		&i.ExerciseID,
		&i.Position,
		&i.Reps,
		&i.WeightGrams,
		&i.CreatedAt,
		&i.Note,
	)
	return i, err
}

const deleteWorkout = `-- name: DeleteWorkout :execrows
DELETE FROM workouts
WHERE id = $1 AND user_id = $2
`

type DeleteWorkoutParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteWorkout(ctx context.Context, arg DeleteWorkoutParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWorkout, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getWorkout = `-- name: GetWorkout :one
SELECT id, user_id, date, type, note, created_at FROM workouts
WHERE id = $1 AND user_id = $2
`

type GetWorkoutParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetWorkout(ctx context.Context, arg GetWorkoutParams) (Workout, error) {
	row := q.db.QueryRow(ctx, getWorkout, arg.ID, arg.UserID)
	var i Workout
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Date,
		&i.Type,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const listExercises = `-- name: ListExercises :many
SELECT id, user_id, name, created_at FROM exercises
WHERE user_id = $1
ORDER BY name ASC
`

func (q *Queries) ListExercises(ctx context.Context, userID uuid.UUID) ([]Exercise, error) {
	rows, err := q.db.Query(ctx, listExercises, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Exercise
	for rows.Next() {
		var i Exercise
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSetsByWorkout = `-- name: ListSetsByWorkout :many
SELECT ws.position, ws.reps, ws.weight_grams, ws.note, e.name AS exercise_name
FROM workout_sets ws
JOIN exercises e ON e.id = ws.exercise_id
WHERE ws.workout_id = $1
ORDER BY ws.position ASC
`

type ListSetsByWorkoutRow struct {
	Position     int32  `json:"position"`
	Reps         *int32 `json:"reps"`
	WeightGrams  *int32 `json:"weight_grams"`
	Note         string `json:"note"`
	ExerciseName string `json:"exercise_name"`
}

func (q *Queries) ListSetsByWorkout(ctx context.Context, workoutID uuid.UUID) ([]ListSetsByWorkoutRow, error) {
	rows, err := q.db.Query(ctx, listSetsByWorkout, workoutID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSetsByWorkoutRow
	for rows.Next() {
		var i ListSetsByWorkoutRow
		if err := rows.Scan(
			&i.Position,
			&i.Reps,
			&i.WeightGrams,
			&i.Note,
			&i.ExerciseName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSetsByWorkoutIDs = `-- name: ListSetsByWorkoutIDs :many
SELECT ws.workout_id, ws.position, ws.reps, ws.weight_grams, ws.note, e.name AS exercise_name
FROM workout_sets ws
JOIN exercises e ON e.id = ws.exercise_id
WHERE ws.workout_id = ANY($1::uuid[])
ORDER BY ws.position ASC
`

type ListSetsByWorkoutIDsRow struct {
	WorkoutID    uuid.UUID `json:"workout_id"`
	Position     int32     `json:"position"`
	Reps         *int32    `json:"reps"`
	WeightGrams  *int32    `json:"weight_grams"`
	Note         string    `json:"note"`
	ExerciseName string    `json:"exercise_name"`
}

func (q *Queries) ListSetsByWorkoutIDs(ctx context.Context, workoutIds []uuid.UUID) ([]ListSetsByWorkoutIDsRow, error) {
	rows, err := q.db.Query(ctx, listSetsByWorkoutIDs, workoutIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSetsByWorkoutIDsRow
	for rows.Next() {
		var i ListSetsByWorkoutIDsRow
		if err := rows.Scan(
			&i.WorkoutID,
			&i.Position,
			&i.Reps,
			&i.WeightGrams,
			&i.Note,
			&i.ExerciseName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkouts = `-- name: ListWorkouts :many
SELECT id, user_id, date, type, note, created_at FROM workouts
WHERE user_id = $1
  AND ($2::date IS NULL OR date >= $2)
  AND ($3::date   IS NULL OR date <= $3)
ORDER BY date DESC, created_at DESC
`

type ListWorkoutsParams struct {
	UserID uuid.UUID  `json:"user_id"`
	From   *time.Time `json:"from"`
	To     *time.Time `json:"to"`
}

func (q *Queries) ListWorkouts(ctx context.Context, arg ListWorkoutsParams) ([]Workout, error) {
	rows, err := q.db.Query(ctx, listWorkouts, arg.UserID, arg.From, arg.To)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workout
	for rows.Next() {
		var i Workout
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Date,
			&i.Type,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertExercise = `-- name: UpsertExercise :one
INSERT INTO exercises (user_id, name)
VALUES ($1, $2)
ON CONFLICT (user_id, lower(name)) DO UPDATE SET name = exercises.name
RETURNING id, user_id, name, created_at
`

type UpsertExerciseParams struct {
	UserID uuid.UUID `json:"user_id"`
	Name   string    `json:"name"`
}

// Crea el ejercicio o, si ya existe (mismo user + lower(name)), devuelve el actual.
func (q *Queries) UpsertExercise(ctx context.Context, arg UpsertExerciseParams) (Exercise, error) {
	row := q.db.QueryRow(ctx, upsertExercise, arg.UserID, arg.Name)
	var i Exercise
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}
