// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transactions.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (user_id, type, amount, occurred_on, cycle, category, remark)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, type, amount, occurred_on, cycle, category, remark, source, external_id, created_at, updated_at
`

type CreateTransactionParams struct {
	UserID     uuid.UUID `json:"user_id"`
	Type       string    `json:"type"`
	Amount     int64     `json:"amount"`
	OccurredOn time.Time `json:"occurred_on"`
	Cycle      time.Time `json:"cycle"`
	Category   string    `json:"category"`
	Remark     string    `json:"remark"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.UserID,
		arg.Type,
		arg.Amount,
		arg.OccurredOn,
		arg.Cycle,
		arg.Category,
		arg.Remark,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Amount,
		&i.OccurredOn,
		&i.Cycle,
		&i.Category,
		&i.Remark,
		&i.Source,
		&i.ExternalID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTransaction = `-- name: DeleteTransaction :execrows
DELETE FROM transactions
WHERE id = $1 AND user_id = $2
`

type DeleteTransactionParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteTransaction(ctx context.Context, arg DeleteTransactionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTransaction, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listTransactionsByCycle = `-- name: ListTransactionsByCycle :many
SELECT id, user_id, type, amount, occurred_on, cycle, category, remark, source, external_id, created_at, updated_at FROM transactions
WHERE user_id = $1 AND cycle = $2
ORDER BY occurred_on DESC, created_at DESC
`

type ListTransactionsByCycleParams struct {
	UserID uuid.UUID `json:"user_id"`
	Cycle  time.Time `json:"cycle"`
}

func (q *Queries) ListTransactionsByCycle(ctx context.Context, arg ListTransactionsByCycleParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactionsByCycle, arg.UserID, arg.Cycle)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Amount,
			&i.OccurredOn,
			&i.Cycle,
			&i.Category,
			&i.Remark,
			&i.Source,
			&i.ExternalID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const summarizeCycle = `-- name: SummarizeCycle :one
SELECT
    COALESCE(SUM(amount) FILTER (WHERE type = 'income'), 0)::bigint  AS income,
    COALESCE(SUM(amount) FILTER (WHERE type = 'expense'), 0)::bigint AS expense
FROM transactions
WHERE user_id = $1 AND cycle = $2
`

type SummarizeCycleParams struct {
	UserID uuid.UUID `json:"user_id"`
	Cycle  time.Time `json:"cycle"`
}

type SummarizeCycleRow struct {
	Income  int64 `json:"income"`
	Expense int64 `json:"expense"`
}

func (q *Queries) SummarizeCycle(ctx context.Context, arg SummarizeCycleParams) (SummarizeCycleRow, error) {
	row := q.db.QueryRow(ctx, summarizeCycle, arg.UserID, arg.Cycle)
	var i SummarizeCycleRow
	err := row.Scan(&i.Income, &i.Expense)
	return i, err
}

const summarizeCycles = `-- name: SummarizeCycles :many
SELECT
    cycle,
    COALESCE(SUM(amount) FILTER (WHERE type = 'income'), 0)::bigint  AS income,
    COALESCE(SUM(amount) FILTER (WHERE type = 'expense'), 0)::bigint AS expense
FROM transactions
WHERE user_id = $1
GROUP BY cycle
ORDER BY cycle DESC
`

type SummarizeCyclesRow struct {
	Cycle   time.Time `json:"cycle"`
	Income  int64     `json:"income"`
	Expense int64     `json:"expense"`
}

func (q *Queries) SummarizeCycles(ctx context.Context, userID uuid.UUID) ([]SummarizeCyclesRow, error) {
	rows, err := q.db.Query(ctx, summarizeCycles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SummarizeCyclesRow
	for rows.Next() {
		var i SummarizeCyclesRow
		if err := rows.Scan(&i.Cycle, &i.Income, &i.Expense); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertImportedTransaction = `-- name: UpsertImportedTransaction :one
INSERT INTO transactions (user_id, type, amount, occurred_on, cycle, category, remark, source, external_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, 'import', $8)
ON CONFLICT (user_id, external_id) WHERE external_id IS NOT NULL
DO UPDATE SET
    type = EXCLUDED.type,
    amount = EXCLUDED.amount,
    occurred_on = EXCLUDED.occurred_on,
    cycle = EXCLUDED.cycle,
    category = EXCLUDED.category,
    remark = EXCLUDED.remark,
    updated_at = now()
RETURNING id, user_id, type, amount, occurred_on, cycle, category, remark, source, external_id, created_at, updated_at
`

type UpsertImportedTransactionParams struct {
	UserID     uuid.UUID `json:"user_id"`
	Type       string    `json:"type"`
	Amount     int64     `json:"amount"`
	OccurredOn time.Time `json:"occurred_on"`
	Cycle      time.Time `json:"cycle"`
	Category   string    `json:"category"`
	Remark     string    `json:"remark"`
	ExternalID *string   `json:"external_id"`
}

func (q *Queries) UpsertImportedTransaction(ctx context.Context, arg UpsertImportedTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, upsertImportedTransaction,
		arg.UserID,
		arg.Type,
		arg.Amount,
		arg.OccurredOn,
		arg.Cycle,
		arg.Category,
		arg.Remark,
		arg.ExternalID,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Amount,
		&i.OccurredOn,
		&i.Cycle,
		&i.Category,
		&i.Remark,
		&i.Source,
		&i.ExternalID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
