/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as MetasRouteImport } from './routes/metas'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FinanzasRouteImport } from './routes/finanzas'
import { Route as EntrenamientoRouteImport } from './routes/entrenamiento'
import { Route as DisciplinaRouteImport } from './routes/disciplina'
import { Route as CheckInRouteImport } from './routes/check-in'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AsistenteIndexRouteImport } from './routes/asistente.index'
import { Route as AsistenteNewRouteImport } from './routes/asistente.new'
import { Route as AsistenteThreadIdRouteImport } from './routes/asistente.$threadId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const MetasRoute = MetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanzasRoute = FinanzasRouteImport.update({
  id: '/finanzas',
  path: '/finanzas',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrenamientoRoute = EntrenamientoRouteImport.update({
  id: '/entrenamiento',
  path: '/entrenamiento',
  getParentRoute: () => rootRouteImport,
} as any)
const DisciplinaRoute = DisciplinaRouteImport.update({
  id: '/disciplina',
  path: '/disciplina',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckInRoute = CheckInRouteImport.update({
  id: '/check-in',
  path: '/check-in',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AsistenteIndexRoute = AsistenteIndexRouteImport.update({
  id: '/asistente/',
  path: '/asistente/',
  getParentRoute: () => rootRouteImport,
} as any)
const AsistenteNewRoute = AsistenteNewRouteImport.update({
  id: '/asistente/new',
  path: '/asistente/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AsistenteThreadIdRoute = AsistenteThreadIdRouteImport.update({
  id: '/asistente/$threadId',
  path: '/asistente/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/check-in': typeof CheckInRoute
  '/disciplina': typeof DisciplinaRoute
  '/entrenamiento': typeof EntrenamientoRoute
  '/finanzas': typeof FinanzasRoute
  '/login': typeof LoginRoute
  '/metas': typeof MetasRoute
  '/register': typeof RegisterRoute
  '/asistente/$threadId': typeof AsistenteThreadIdRoute
  '/asistente/new': typeof AsistenteNewRoute
  '/asistente/': typeof AsistenteIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/check-in': typeof CheckInRoute
  '/disciplina': typeof DisciplinaRoute
  '/entrenamiento': typeof EntrenamientoRoute
  '/finanzas': typeof FinanzasRoute
  '/login': typeof LoginRoute
  '/metas': typeof MetasRoute
  '/register': typeof RegisterRoute
  '/asistente/$threadId': typeof AsistenteThreadIdRoute
  '/asistente/new': typeof AsistenteNewRoute
  '/asistente': typeof AsistenteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/check-in': typeof CheckInRoute
  '/disciplina': typeof DisciplinaRoute
  '/entrenamiento': typeof EntrenamientoRoute
  '/finanzas': typeof FinanzasRoute
  '/login': typeof LoginRoute
  '/metas': typeof MetasRoute
  '/register': typeof RegisterRoute
  '/asistente/$threadId': typeof AsistenteThreadIdRoute
  '/asistente/new': typeof AsistenteNewRoute
  '/asistente/': typeof AsistenteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/check-in'
    | '/disciplina'
    | '/entrenamiento'
    | '/finanzas'
    | '/login'
    | '/metas'
    | '/register'
    | '/asistente/$threadId'
    | '/asistente/new'
    | '/asistente/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/check-in'
    | '/disciplina'
    | '/entrenamiento'
    | '/finanzas'
    | '/login'
    | '/metas'
    | '/register'
    | '/asistente/$threadId'
    | '/asistente/new'
    | '/asistente'
  id:
    | '__root__'
    | '/'
    | '/check-in'
    | '/disciplina'
    | '/entrenamiento'
    | '/finanzas'
    | '/login'
    | '/metas'
    | '/register'
    | '/asistente/$threadId'
    | '/asistente/new'
    | '/asistente/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckInRoute: typeof CheckInRoute
  DisciplinaRoute: typeof DisciplinaRoute
  EntrenamientoRoute: typeof EntrenamientoRoute
  FinanzasRoute: typeof FinanzasRoute
  LoginRoute: typeof LoginRoute
  MetasRoute: typeof MetasRoute
  RegisterRoute: typeof RegisterRoute
  AsistenteThreadIdRoute: typeof AsistenteThreadIdRoute
  AsistenteNewRoute: typeof AsistenteNewRoute
  AsistenteIndexRoute: typeof AsistenteIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metas': {
      id: '/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof MetasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finanzas': {
      id: '/finanzas'
      path: '/finanzas'
      fullPath: '/finanzas'
      preLoaderRoute: typeof FinanzasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrenamiento': {
      id: '/entrenamiento'
      path: '/entrenamiento'
      fullPath: '/entrenamiento'
      preLoaderRoute: typeof EntrenamientoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disciplina': {
      id: '/disciplina'
      path: '/disciplina'
      fullPath: '/disciplina'
      preLoaderRoute: typeof DisciplinaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-in': {
      id: '/check-in'
      path: '/check-in'
      fullPath: '/check-in'
      preLoaderRoute: typeof CheckInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asistente/': {
      id: '/asistente/'
      path: '/asistente'
      fullPath: '/asistente/'
      preLoaderRoute: typeof AsistenteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asistente/new': {
      id: '/asistente/new'
      path: '/asistente/new'
      fullPath: '/asistente/new'
      preLoaderRoute: typeof AsistenteNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asistente/$threadId': {
      id: '/asistente/$threadId'
      path: '/asistente/$threadId'
      fullPath: '/asistente/$threadId'
      preLoaderRoute: typeof AsistenteThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckInRoute: CheckInRoute,
  DisciplinaRoute: DisciplinaRoute,
  EntrenamientoRoute: EntrenamientoRoute,
  FinanzasRoute: FinanzasRoute,
  LoginRoute: LoginRoute,
  MetasRoute: MetasRoute,
  RegisterRoute: RegisterRoute,
  AsistenteThreadIdRoute: AsistenteThreadIdRoute,
  AsistenteNewRoute: AsistenteNewRoute,
  AsistenteIndexRoute: AsistenteIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
